let hypephrases = [`All of this just works.`,
    `Doritos.`,
    `Mountain Dew.`,
    `Fallout 3 will have 200 endings.`,
    `We're not done yet.`,
    `Multiple endings!`,
    `A thousand of the most popular names for him to say.`,
    `Dynamic.`,
    `Radiant quests. Infinite quests!`,
    `Exploration.`,
    `Todd.`,
    `It. Just. Works.`,
    `Immersive Experiences.`,
    `E3 is upon us.`,
    `You can play forever.`,
    `Season Pass.`,
    `This is the golden age of gaming.`,
    `Visceral.`,
    `GOTY`,
    `Epic.`,
    `GOTY confirmed.`,
    `Day-1.`,
    `Content.`,
    `Exclusive Content.`,
    `Cinematic Experience.`,
    `Open world.`,
    `Over 40 thousand lines.`,
    `Downloadable Content.`,
    `Seamless Open World.`,
    `Yes, I was in the chess club.`,
    `Tell me sweet little lies.`,
    `This fall!`,
    `Pre-order confirmed.`,
    `A brave new direction.`,
    `Pushing boundaries.`,
    `This game is the best. It's very great. Very great. Gonna be yuge.`,
    `All aboard!`,
    `Fleetwood Mac.`,
    `Triple-A.`,
    `Make the player proud. Make yourself proud!`,
    `Deep lore.`,
    `Atmospheric.`,
    `It works... it actually works perfectly!`,
    `Second-screen experience.`,
    `Nintendo.`,
    `Microsoft.`,
    `Sony.`,
    `Nvidia.`,
    `AMD.`,
    `Branching paths.`,
    `See that mountain?`,
    `Emotionally Engaging`,
    `Choice and Consequence.`,
    `Bang! There it is.`,
    `One Million Troops.`,
    `Out Industry.`,
    `Extreme.`,
    `An enourmous dynamic world.`,
    `Exploration.`,
    `Pushing boundaries.`,
    `Crafting.`,
    `Tell me lies.`,
    `Over 200 dungeons, all hand-crafted.`,
    `T.O.D.D. H.O.W.A.R.D.`,
    `As far as stupid gimmicks goes, this is the best fucking one I have ever seen.`,
    `Press conference.`,
    `I won't wait for the Gold edition.`,
    `Pre-order c o n f i r m e d.`,
    `Innovative.`,];

    exports.hypephrases = hypephrases