let hypephrases = [`All of this just works.`,
    `Doritos.`,
    `Mountain Dew.`,
    `Dale Cooper in every episode.`,
    `Musical guests such as Venetian Snares and Moby.`,
    `Starring Matthew Lillard.`,
    `Into the lodge.`,
    `Garmonbozia`,
    `Two *brand new* Coopers`,
    `Damn good coffee.`,
    `Showtime.`,
    `It's much more Lynchian...`,
    `Let's rock!`,
    `That gum you like is going to come back in style.`,
    `It's been 25 years.`,
    `The owls are not what they seem.`,
    `When you see me again, it won't be me.`,
    `Fallout 3 will have 200 endings.`,
    `We're not done yet.`,
    `Multiple endings!`,
    `A thousand of the most popular names for him to say.`,
    `Dynamic.`,
    `Radiant quests. Infinite quests!`,
    `Exploration.`,
    `Todd will be at e3 2017.`,
    `Relive the classic world of Skyrim`,
    `XBOX ONE X.`,
    `Mario meets Rabbids.`,
    `Mario becomes Dinosaurs.`,
    `Need for Speed: Payback`,
    `Got my boy Marcus, Executive Producer here, he is the producer of the game. Thank you Nick, for having me.`,
    `It. Just. Works.`,
    `Immersive Experiences.`,
    `E3 is upon us.`,
    `You can play forever.`,
    `Season Pass.`,
    `This is the golden age of gaming.`,
    `Visceral.`,
    `Game of the Year All Years`,
    `GOTY confirmed.`,
    `Day-1.`,
    `Content.`,
    `Exclusive Content.`,
    `Cinematic Experience.`,
    `Open world.`,
    `Over 40 thousand lines.`,
    `Downloadable Content.`,
    `Seamless Open World.`,
    `Yes, I was in the chess club.`,
    `Tell me sweet little lies.`,
    `This fall!`,
    `Pre-order confirmed.`,
    `A brave new direction.`,
    `Pushing boundaries.`,
    `This game is the best. It's very great. Very great. Gonna be yuge.`,
    `All aboard!`,
    `Fleetwood Mac.`,
    `Triple-A.`,
    `Make the player proud. Make yourself proud!`,
    `Deep lore.`,
    `Atmospheric.`,
    `It works... it actually works perfectly!`,
    `Second-screen experience.`,
    `Nintendo.`,
    `Microsoft.`,
    `Sony.`,
    `Nvidia.`,
    `AMD.`,
    `Branching paths.`,
    `See that mountain?`,
    `Emotionally Engaging`,
    `Choice and Consequence.`,
    `Bang! There it is.`,
    `One Million Troops.`,
    `Our Industry.`,
    `Extreme.`,
    `An enourmous dynamic world.`,
    `Exploration.`,
    `Pushing boundaries.`,
    `Crafting.`,
    `Tell me lies.`,
    `Over 200 dungeons, all hand-crafted.`,
    `T.O.D.D. H.O.W.A.R.D.`,
    `As far as stupid gimmicks goes, this is the best fucking one I have ever seen.`,
    `Press conference.`,
    `I won't wait for the Gold edition.`,
    `Pre-order c o n f i r m e d.`,
    `Innovative.`,];

    exports.hypephrases = hypephrases